# Generated by Django 5.1.1 on 2024-10-05 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_todo_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["-created"]},
        ),
    ]
